<div class="table-info">
		<div class="table-header">
			<div class="table-caption">
				Liste des catégories
			</div>
		</div>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Nom du catalogue</th>
					<th>Produits liés</th>
					<th>Editer</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->categories as $category):;?>
		<tr>
			<td><?php echo $category->getName();?></td>
			<td>Pas de produits</td>
			<td><a class="btn btn-warning btn-rounded" href="<?php echo $this->url('category', array('action' => 'edit','id'=> $category->getId()));?>">Edit</a></td>	
		</tr>
		 <?php endforeach; ?>
	</tbody>
</table>