<?php if(count($this->categories) == 0):?>
<div class="alert alert-info">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>Pas de catégories !</strong> Aucune catégories pour le moment.
</div>
<?php else:?>
<div class="table-info">
		<div class="table-header">
			<div class="table-caption">
				Liste des catégories
			</div>
		</div>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Nom du catalogue</th>
					<th>Produits liés</th>
					<th>Créer un produit</th>
					<th>Editer</th>	
					<th>Supprimer</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->categories as $category):;?>
		<tr>
			<td><?php echo $category->getName();?></td>
			<?php
			 if(count($category->getProducts())== 0):?>
				<td>pas de produits</td>
			<?php else: ?>
    				<td><a class="btn btn-info btn-rounded" href="<?php echo $this->url('product', array('action' => 'index','id_category'=>$category->getId()));?>">Voir les produits</a></td>
    			<?php endif;?>
    		<td><a class="btn btn-primary btn-rounded" href="<?php echo $this->url('product', array('action' => 'new','id_category'=> $category->getId()));?>">Créer</a></td>
			<td><a class="btn btn-warning btn-rounded" href="<?php echo $this->url('category', array('action' => 'edit','id'=> $category->getId()));?>">Edit</a></td>	
			<td><a class="btn btn-danger btn-rounded" href="<?php echo $this->url('category', array('action' => 'delete','id'=> $category->getId()));?>">Supprimer</a></td>	
		</tr>
		 <?php endforeach; ?>
	</tbody>
</table>
<?php endif;?>