<div class="row">
	<div class="col-xs-12">
	<?php   $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('category', array('action' => 'new')));
	$form->prepare();?>
	<?php  echo $this->form()->openTag($form);?>
		 <?php echo $this->formInput($form->get('id')); ?>
		<div class="panel-heading">
			<span class="panel-title">Création d'un catalogue:</span>
		</div>
		<div class="panel-body no-padding-hr">
			<div class="form-group no-margin-hr panel-padding-h no-padding-t no-border-t">
				<div class="row">
					<label class="col-sm-4 control-label">Nom:</label>
					<div class="col-sm-8">
					 <?php    
					      echo $this->formInput($form->get('name'));
						  echo $this->formElementErrors($form->get('submit'));
						?>
					</div>
				</div>
			</div>
			<div class="panel-footer text-right">
				<button class="btn btn-primary">Envoyer</button>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
</div>
