<div class="row">
	<div class="col-xs-12">
	<?php   $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('product', array('action' => 'edit','id_category'=>$this->id_category,'id'=>$this->id,)));
	$form->prepare();?>
	<?php  echo $this->form()->openTag($form);?>
	<?php echo $this->formInput($form->get('id')); ?>
		<div class="panel-heading">
			<span class="panel-title">Edition d'un produit	:</span>
		</div>
		<div class="panel-body no-padding-hr">
			<div class="form-group no-margin-hr panel-padding-h no-padding-t no-border-t">
				<div class="row">
					 <?php echo $this->formLabel($form->get('name'));?>
					<div class="col-sm-8">
        			 <?php echo $this->formInput($form->get('name'));?>			
        			</div>
				</div>
			</div>
			<div class="form-group no-margin-hr panel-padding-h no-padding-t no-border-t">
				<div class="row">
					 <?php echo $this->formLabel($form->get('price'));?>
					<div class="col-sm-8">
        			 <?php echo $this->formInput($form->get('price'));?>			
        			</div>
				</div>
			</div>
			<div class="form-group no-margin-hr panel-padding-h no-padding-t no-border-t">
				<div class="row">
					 <?php echo $this->formLabel($form->get('shortDesc'));?>
					<div class="col-sm-8">
        			 <?php echo $this->formInput($form->get('shortDesc'));?>			
        			</div>
				</div>
			</div>
			<div class="form-group no-margin-hr panel-padding-h no-padding-t no-border-t">
				<div class="row">
					  <?php echo $this->formLabel($form->get('longDesc'));?>
					<div class="col-sm-8">
        			 <?php echo $this->formInput($form->get('longDesc'));?>			
        			</div>
				</div>
			</div>
			<div class="panel-footer text-right">
				<button class="btn btn-primary">Envoyer</button>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
</div>
