<?php if(count($this->categories) == 0):?>
<div class="alert alert-info">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>Pas de catégories !</strong> Aucune catégories pour le moment.
</div>
<?php else:?>
<?php $paging = $this->paginationHelper($this->paginator, $this->page, '/category/', 1);?>
<div class="table-info">
		<div class="table-header">
			<div class="table-caption">
				Liste des catégories
			</div>
		</div>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Nom du catalogue</th>
					<th>Produits liés</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->categories as $category):;?>
		<tr>
			<td><?php echo $category->getName();?></td>
			<?php
			 if(count($category->getProducts())== 0):?>
				<td>pas de produits</td>
			<?php else: ?>
    				<td><a class="btn btn-info btn-rounded" href="<?php echo $this->url('fo-product', array('action' => 'index','id_category'=>$category->getId()));?>">Voir les produits</a></td>
    		<?php endif;?>
		</tr>
		 <?php endforeach; ?>
	</tbody>
</table>
<?php echo $paging; ?>
<?php endif;?>