<h1><?php echo $this->category->getName() ?></h1>
<div class="row">

    <?php foreach ($this->category->getProducts() as $product) :?>
        <div class="col-md-3 col-sm-6">
            <div class="product">
                <div class="product-image">
                    <img src="img/product-2.jpg" alt="">
                </div>
                <h2><a href="/product/<?php echo$product->getId()?>"><?php echo$product->getName()?></a></h2>
                <div class="price">
                    <?php echo$product->getPrice()?>
                </div>
                <button>toto</button>
            </div>
        </div>
    <?php endforeach?>
</div>
