<div class="panel widget-tasks panel-dark-gray">
	<div class="panel-heading">
		<span class="panel-title"><i class="panel-title-icon fa fa-tasks"></i>Produits récents</span>
		<div class="panel-heading-controls">
		</div>
	</div> <!-- / .panel-heading -->
	<!-- Without vertical padding -->
	<div class="panel-body no-padding-vr ui-sortable">
	<?php foreach($this->products as $product):;?>
		<div class="task">
			<span class="label label-success pull-right">Prix: <?php echo $product->getPrice();?> €</span>
			<div class="fa fa-arrows-v task-sort-icon"></div>	
			<a href="#" class="task-title"><?php echo $product->getName();?><span><?php echo $product->getShortDesc();?></span></a>
		</div> <!-- / .task -->
	<?php endforeach;?>
	</div> <!-- / .panel-body -->
</div>