<div class="col-sm-offset-4 col-sm-8">
    <h1><?php echo $this->product->getName() ?></h1>
    <h2><?php echo $this->product->getPrice() ?> $</h2>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="home">
            <h2>Description du produit</h2>
            <p><?php echo $this->product->getLongDesc() ?></p>
        </div>
    </div>
    <?php   $form = $this->form; ?>
	<?php $form->setAttribute('action', $this->url('fo-product', array('action' => 'show','id_category'=> $this->id_category, 'id' =>$this->product->getId())));
	$form->prepare();?>
    <?php  echo $this->form()->openTag($this->form)?>
    <div class="panel-heading col-sm-4">
        <span class="panel-title">Ajouter ce produit à ma liste de souhaits	:</span>
	    <?php echo $this->formInput($this->form->get('product_id'));?>
     		<button class="btn btn-primary">Ajouter</button>
		<?php echo $this->form()->closeTag($this->form); ?>
    </div>
</div>