<ul class="breadcrumb breadcrumb-page">
	<div class="breadcrumb-label text-light-gray">Vous êtes ici: </div>
	<li><a href="/">Home</a></li>
	<li class="active"><a href="#">Back office</a></li>
</ul>
<div class="page-header">

	<div class="row">
		<!-- Page header, center on small screens -->
		<h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-dashboard page-header-icon"></i>&nbsp;&nbsp;Back office</h1>

		<div class="col-xs-12 col-sm-8">
			<div class="row">
				<hr class="visible-xs no-grid-gutter-h">
				<!-- "Create project" button, width=auto on desktops -->
				<div class="pull-right col-xs-12 col-sm-auto"><a href="/bo/quizz/create" class="btn btn-primary btn-labeled" style="width: 100%;"><span class="btn-label icon fa fa-plus"></span>Créer un quizz</a></div>

				<!-- Margin -->
				<div class="visible-xs clearfix form-group-margin"></div>
			</div>
		</div>
	</div>
</div> <!-- / .page-header -->