<div id="main-navbar" class="navbar navbar-inverse" role="navigation">
		<div class="navbar-inner">
			<!-- Main navbar header -->
			<div class="navbar-header">

				<!-- Logo -->
				<a href="/" class="navbar-brand">
					Vitrine
				</a>

				<!-- Main navbar toggle -->
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

			</div> <!-- / .navbar-header -->

			<div id="main-navbar-collapse" class="navbar-collapse main-navbar-collapse collapse" style="height: 0.8px;">
				<div>
					<ul class="nav navbar-nav">
						<li>
							<a href="/">Home</a>
						</li>
						<?php if($this->layout()->authService->hasIdentity() and $this->layout()->authService->getIdentity()->getStatus() == "admin"):;?>		
						<li>
							<a href="/bo/category">Vue admin</a>
						</li>
						<?php endif; ?>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Catégories</a>
							<ul class="dropdown-menu">
							<?php foreach ($this->layout()->categories as $category) : ?>
								<li>
									<a href="<?php echo $this->url('fo-product', array('action' => 'index','id_category'=>$category->getId()));?>"><?php echo $category->getName()?></a>
								</li>
							<?php endforeach?>	</ul>
						</li>
					</ul> <!-- / .navbar-nav -->

					<div class="right clearfix">
						<ul class="nav navbar-nav pull-right right-navbar-nav">
						<?php if($this->layout()->authService->hasIdentity()):;?>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
								<span><?php echo $this->layout()->authService->getIdentity()->getName();?></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="/login/logout"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
							</ul>
						</li>
						<?php else:;?>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
								<span>Pas connecté</span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="/login"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Se connecter</a></li>
							</ul>
						</li>
						<?php endif;?>
					
						</ul> <!-- / .navbar-nav -->
					</div> <!-- / .right -->
				</div>
			</div> <!-- / #main-navbar-collapse -->
		</div> <!-- / .navbar-inner -->
	</div>