<div id="main-navbar" class="navbar navbar-inverse" role="navigation">
	<div class="navbar-inner">
		<!-- Main navbar header -->
		<div class="navbar-header">
			<!-- Logo -->
			<a href="/fo" class="navbar-brand">
				HOME
			</a>
			<!-- Main navbar toggle -->
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

		</div> <!-- / .navbar-header -->

		<div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
			<div>
				<ul class="nav navbar-nav">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
								<span>Categories</span>
							</a>

							<?php foreach ($this->layout()->categories->findAll() as $category) : ?>
								<ul class="dropdown-menu">
									<li>
										<a href="/category/<?php echo $category->getId() ?>">
											<?php echo $category->getName() ?>
										</a>
									</li>
								</ul>
							<?php endforeach?>
						</li>
					</ul> <!-- / .navbar-nav -->
					<!-- / .navbar-nav -->
				<div class="right clearfix">
    					<ul class="nav navbar-nav pull-right right-navbar-nav">
    										<ul class="nav navbar-nav">
        					<li>
        						<a href="/wishlist">Wishlist</a>
        					</li>
    					</ul>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
								<span>User</span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="/bo/logout"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
							</ul>
						</li>
					</ul> <!-- / .navbar-nav -->
				</div> <!-- / .right -->
			</div>
		</div> <!-- / #main-navbar-collapse -->
	</div> <!-- / .navbar-inner -->
</div> <!-- / #main-navbar -->
